CREATE OR REPLACE TABLE `ph-jabri.ICFES.SNIES_07_2O_IDS` 
OPTIONS () AS 
WITH 
SNIES AS (
  SELECT *, 
ROW_NUMBER() OVER (PARTITION BY PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, FECHA_NACIMIENTO, SEXO_BIOLOGICO  ORDER BY ANNIO||SEMESTRE  ASC )  AS RN
 FROM `ph-jabri.ICFES.SNIES_07_2O` 
-- WHERE PRIMER_NOMBRE = 'YENIFER' AND  -- SEGUNDO_NOMBRE  = 'FERNANDA' AND 
-- PRIMER_APELLIDO = 'PERALTA' AND  SEGUNDO_APELLIDO = 'SOSA'
-- ORDER BY 1 ASC
),
SNIES_AGG AS (
  SELECT 
SUFIX,
ANNIO,
-- SEMESTRE,
ID_IES,
IES_NOMBRE,
ID_MUNICIPIO_IES,
MUNICIPIO_IES,
ORIG_CODE,
REPLACE(`ph-jabri.udfs.homg_sintildes`(ORIGEN), ',','')  ORIGEN,
-- TIPO_DOCUMENTO,
STRING_AGG(DISTINCT  NUM_DOCUMENTO , " | ") IDS,
PRIMER_NOMBRE,
SEGUNDO_NOMBRE,
PRIMER_APELLIDO,
SEGUNDO_APELLIDO,
SEXO_BIOLOGICO,
FECHA_NACIMIENTO,
NOMBRE_PROGRAMA,
ID_AREA_CONOCIMIENTO,

CASE 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%LICENCIATURA EN LENGUAS%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'CIENCIAS DE LA EDUCACION' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%LICENCIATURA%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'CIENCIAS DE LA EDUCACION' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%LICENCIATURA EN MATEMATIC%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'CIENCIAS DE LA EDUCACION' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE  '%CIENCIA DE DATOS%'    AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'MATEMATICAS Y CIENCIAS NATURALES' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE  '%QUÍMICA%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'MATEMATICAS Y CIENCIAS NATURALES' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE  '%INGENIERIA DE SISTEMAS%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE  '%INFORMATICA%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE  '%INGENIERIA MECANICA%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE  '%INGENIERIA %' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%DERECHO%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'CIENCIAS SOCIALES Y HUMANAS' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%PSICOLOG%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'CIENCIAS SOCIALES Y HUMANAS' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%FONOAUDIOLO%'     AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION') THEN 'CIENCIAS DE LA SALUD' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%ENFERMERIA%'     AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION') THEN 'CIENCIAS DE LA SALUD' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%NUTRICI_N%'     AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION') THEN 'CIENCIAS DE LA SALUD' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%SALUD EN EL TRABAJO%'   AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION') THEN 'CIENCIAS DE LA SALUD' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%FINANZ%'     AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION') THEN  'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%ECONOM%'     AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION') THEN  'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%MERCADEO%'     AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION') THEN  'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%ADMINISTRACI_N DE EMPRESAS%'     AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION') THEN  'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%ADMINISTRACI_N%'     AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION') THEN  'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%CONTADURÍA%'     AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION') THEN  'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%ADMINISTRACI_N DE NEGOCIOS INTERNACIONALES%'     AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION') THEN  'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'

WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%SOCIAL%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%HUMANAS%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%FILOSOF%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'CIENCIAS SOCIALES Y HUMANAS'
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%ARTE%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%MUSICA%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%DISEÑO%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'BELLAS ARTES' 
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%INGENIER%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%ARQUITECTUR%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%URBANISMO%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES'
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%SALUD%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%MEDICIN%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%ENFERMER%' THEN 'CIENCIAS DE LA SALUD'  
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%EDUCACION%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%PEDAGOGI%' THEN 'CIENCIAS DE LA EDUCACION'
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%ADMINISTRATIV%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%CONTABILIDAD%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%ECONOM%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%FINANZAS%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%NEGOCIOS%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%AGRO%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%PECUAR%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%VETERINAR%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'AGRONOMIA VETERINARIA Y AFINES'
WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%MATEMATIC%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%FISIC%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%QUIMIC%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%BIOLOGI%' AND (AREA_CONOCIMIENTO ='' OR AREA_CONOCIMIENTO = 'SIN INFORMACION')  THEN 'MATEMATICAS Y CIENCIAS NATURALES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%CONSTRUCCION%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%INGENIERIA%' THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%AMBIENTAL%' THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%LOGISTICA%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%CONTABLE%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%FINANCIERA%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%REDES%' THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES' 
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%BASES DE DATOS%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%COMERCIO%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%PROCESAMIENTO DE ALIMENTOS%' THEN 'AGRONOMIA VETERINARIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%SOFTWARE%' THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%PRENSA%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%MEDIOS%' THEN 'CIENCIAS SOCIALES Y HUMANAS' 
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%MERCADO%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%COMERCIAL%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%AEREO%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%INDUSTRIAL%' THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%TELECOMUNICACIONES%' THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES' 
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%TERMINALES%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%PORTUARIAS%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%PRODUCTOS%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%CREATIVO%' THEN 'BELLAS ARTES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%CONTADURIA%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%TURISMO%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%HOTELERA%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%HUMANA%' THEN 'CIENCIAS SOCIALES Y HUMANAS'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%INFRAESTRUCTURA%' AND REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%INFORMATICA%' THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES' 
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%COMERCIAL%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%TOPOGRAFIA%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%GEOREFERENCIACION%' THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES'  
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%ELECTRICIDAD%' THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%CONTABLE%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%DEPORTIVO%' THEN 'CIENCIAS DE LA SALUD'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%FOTOGRAFIA%' THEN 'BELLAS ARTES' 
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%TRANSPORTE%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%LOGISTICA%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%ALIMENTOS%' THEN 'AGRONOMIA VETERINARIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%MODA%' THEN 'BELLAS ARTES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%GASTRONOMIA%' THEN 'AGRONOMIA VETERINARIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%PROCESOS CONTABLES%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%TRIBUTARIA%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%CONTABLE%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%FINANCIERA%' THEN 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%GAS%' THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%MEDIOS GRAFICOS%' OR REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%VISUALES%' THEN 'BELLAS ARTES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%TELECOMUNICACIONES%' THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES' 
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%CONSTRUCCION%' THEN 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES'
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%CRIMINAL%' THEN 'CIENCIAS SOCIALES Y HUMANAS' 
    WHEN REPLACE(`ph-jabri.udfs.homg_sintildes`(NOMBRE_PROGRAMA), ',','')  LIKE '%CIENCIAS DE LA TIERRA%' THEN 'MATEMATICAS Y CIENCIAS NATURALES'

ELSE AREA_CONOCIMIENTO
END AREA_CONOCIMIENTO, 
ID_NBC,
NBC,
STRING_AGG(DISTINCT ID_MUN_PROGRAMA , " | ")  ID_MUN_PROGRAMA,
STRING_AGG(DISTINCT MUN_PROGRAMA , " | ")  MUN_PROGRAMA,


 FROM SNIES WHERE RN <= 2
group by 1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,19,20 
)
SELECT DISTINCT * except(AREA_CONOCIMIENTO),

CASE 
    WHEN AREA_CONOCIMIENTO = 'ECONOMIA ADMINISTRACION CONTADURIA Y AFINES' 
        THEN 'ECONOMICS, BUSINESS ADMINISTRATION, ACCOUNTING, AND RELATED FIELDS'
    WHEN AREA_CONOCIMIENTO = 'CIENCIAS DE LA EDUCACION' 
        THEN 'EDUCATION SCIENCES'
    WHEN AREA_CONOCIMIENTO = 'INGENIERIA ARQUITECTURA URBANISMO Y AFINES' 
        THEN 'ENGINEERING, ARCHITECTURE, URBAN PLANNING, AND RELATED FIELDS'
    WHEN AREA_CONOCIMIENTO = 'BELLAS ARTES' 
        THEN 'FINE ARTS'
    WHEN AREA_CONOCIMIENTO = 'CIENCIAS SOCIALES Y HUMANAS' 
        THEN 'SOCIAL SCIENCES AND HUMANITIES'
    WHEN AREA_CONOCIMIENTO = 'CIENCIAS DE LA SALUD'
        THEN 'HEALTH SCIENCES'
    WHEN AREA_CONOCIMIENTO = 'MATEMATICAS Y CIENCIAS NATURALES' 
        THEN 'MATHEMATICS AND NATURAL SCIENCES'
    WHEN AREA_CONOCIMIENTO = 'AGRONOMIA VETERINARIA Y AFINES' 
    THEN 'AGRONOMY, VETERINARY MEDICINE, AND RELATED FIELDS'
    ELSE AREA_CONOCIMIENTO end AREA_CONOCIMIENTO ,

CASE WHEN NOMBRE_PROGRAMA LIKE '%TECNOL%' THEN 'Technological Program'
     WHEN NOMBRE_PROGRAMA LIKE '%TECNI%' OR NOMBRE_PROGRAMA LIKE '%TÉCNI%' THEN 'Technical Program'
     ELSE 'University Program' END AS LEVEL,


CASE 
    WHEN IDS LIKE '% |%' THEN SPLIT(IDS, " | ")[SAFE_OFFSET(0)]
        ELSE IDS END ID1,

CASE WHEN IDS LIKE '% | %' THEN SPLIT(IDS, " | ")[SAFE_OFFSET(1)]
ELSE IDS END ID2

FROM SNIES_AGG











