CREATE OR REPLACE TABLE `ph-jabri.SABER_PRO.UNCLEAN_SBPRO_2006_2022` 
OPTIONS () AS
WITH 
SBPRO_2021 AS (
  SELECT 
ESTU_TIPODOCUMENTO , ESTU_NACIONALIDAD , ESTU_GENERO , ESTU_FECHANACIMIENTO  ,  ESTU_EXTERIOR  , -- 5
PERIODO  , ESTU_CONSECUTIVO  , ESTU_ESTUDIANTE  , ESTU_PAIS_RESIDE  , ESTU_DEPTO_RESIDE ,-- 10
ESTU_COD_RESIDE_DEPTO , ESTU_MCPIO_RESIDE , ESTU_COD_RESIDE_MCPIO , ESTU_AREARESIDE  ,  ESTU_COLE_TERMINO ,-- 15
ESTU_CODDANE_COLE_TERMINO , ESTU_COD_COLE_MCPIO_TERMINO , ESTU_TITULOOBTENIDOBACHILLER , ESTU_VALORMATRICULAUNIVERSIDAD , ESTU_PAGOMATRICULABECA , --20
ESTU_PAGOMATRICULACREDITO , ESTU_PAGOMATRICULAPADRES , ESTU_PAGOMATRICULAPROPIO  , ESTU_COMOCAPACITOEXAMENSB11  ,  ESTU_TIPODOCUMENTOSB11 , --25
ESTU_SEMESTRECURSA  , FAMI_EDUCACIONPADRE  , FAMI_EDUCACIONMADRE ,  FAMI_TRABAJOLABORPADRE , FAMI_TRABAJOLABORMADRE , --30
SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC) FAMI_ESTRATOVIVIENDA , ESTU_OTROCOLE_TERMINO , FAMI_TIENEINTERNET , 
FAMI_TIENECOMPUTADOR , FAMI_TIENELAVADORA , --35
FAMI_TIENEHORNOMICROOGAS , FAMI_TIENESERVICIOTV , FAMI_TIENEAUTOMOVIL , FAMI_TIENEMOTOCICLETA , FAMI_TIENECONSOLAVIDEOJUEGOS , --40 
FAMI_CUANTOSCOMPARTEBA_O , ESTU_PRESENTACIONCASA , ESTU_PAISDOCUMENTOS11 , ESTU_HORASSEMANATRABAJA , CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION , --45
INST_NOMBRE_INSTITUCION , ESTU_PRGM_ACADEMICO , ESTU_SNIES_PRGMACADEMICO , GRUPOREFERENCIA , ESTU_PRGM_CODMUNICIPIO , --50
ESTU_PRGM_MUNICIPIO , ESTU_PRGM_DEPARTAMENTO , ESTU_NIVEL_PRGM_ACADEMICO ,  ESTU_METODO_PRGM , ESTU_NUCLEO_PREGRADO , --55
ESTU_INST_CODMUNICIPIO , ESTU_INST_MUNICIPIO , ESTU_INST_DEPARTAMENTO , INST_CARACTER_ACADEMICO , INST_ORIGEN , --60
ESTU_PRIVADO_LIBERTAD ,  ESTU_COD_MCPIO_PRESENTACION , ESTU_MCPIO_PRESENTACION , ESTU_DEPTO_PRESENTACION , ESTU_COD_DEPTO_PRESENTACION , --65
MOD_RAZONA_CUANTITAT_PUNT , MOD_RAZONA_CUANTITAT_DESEM , MOD_RAZONA_CUANTITATIVO_PNAL , MOD_RAZONA_CUANTITATIVO_PNBC , MOD_LECTURA_CRITICA_PUNT , --70 
CAST( MOD_LECTURA_CRITICA_DESEM AS STRING) MOD_LECTURA_CRITICA_DESEM , MOD_LECTURA_CRITICA_PNAL , MOD_LECTURA_CRITICA_PNBC , MOD_COMPETEN_CIUDADA_PUNT , MOD_COMPETEN_CIUDADA_DESEM , --75 
MOD_COMPETEN_CIUDADA_PNAL , MOD_COMPETEN_CIUDADA_PNBC , MOD_INGLES_PUNT , MOD_INGLES_DESEM , MOD_INGLES_PNAL ,--80
MOD_INGLES_PNBC , MOD_COMUNI_ESCRITA_PUNT , MOD_COMUNI_ESCRITA_DESEM , MOD_COMUNI_ESCRITA_PNAL , MOD_COMUNI_ESCRITA_PNBC , --85
 PUNT_GLOBAL , PERCENTIL_NBC , PERCENTIL_GLOBAL , ESTU_INSE_INDIVIDUAL ,CAST(ESTU_NSE_INDIVIDUAL AS STRING)  ESTU_NSE_INDIVIDUAL , --90 
ESTU_NSE_IES

FROM `ph-jabri.SABER_PRO.SBPRO_2021`  where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
LIMIT 3
),
SBPRO_2006 AS (
  SELECT
EVAL_TIPODOCUMENTO ESTU_TIPODOCUMENTO,
'' ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
ESTU_NACIMIENTO_DIA || '/'|| ESTU_NACIMIENTO_MES || '/'|| CAST(ESTU_NACIMIENTO_ANNO AS STRING) ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
PRUEBA AS PERIODO,
ESTU_CONSECUTIVO,
'' ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
'' ESTU_DEPTO_RESIDE  -- 10 COLUMN
,LEFT(ESTU_RESIDE_CODMPIO, 2) ESTU_COD_RESIDE_DEPTO,
'' ESTU_MCPIO_RESIDE,
ESTU_RESIDE_CODMPIO ESTU_COD_RESIDE_MCPIO
,CASE WHEN ECON_AREAVIVE =1 THEN 'Cabecera municipal'
      WHEN ECON_AREAVIVE =2 THEN 'Area rural' else null end ESTU_AREARESIDE  
,'' ESTU_COLE_TERMINO             -- 15 COLUMN
,NULL ESTU_CODDANE_COLE_TERMINO 
,'' ESTU_COD_COLE_MCPIO_TERMINO
,'' ESTU_TITULOOBTENIDOBACHILLER 
,'' ESTU_VALORMATRICULAUNIVERSIDAD  
,'' ESTU_PAGOMATRICULABECA          -- 20 COLUMN
,'' ESTU_PAGOMATRICULACREDITO
,'' ESTU_PAGOMATRICULAPADRES
,'' ESTU_PAGOMATRICULAPROPIO
,'' ESTU_COMOCAPACITOEXAMENSB11     
,'' ESTU_TIPODOCUMENTOSB11          -- 25
,ESTU_SEMESTRE_CURSANDO ESTU_SEMESTRECURSA
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_PADRE as numeric)) FAMI_EDUCACIONPADRE 
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_MADRE as numeric))  FAMI_EDUCACIONMADRE
,FAMI_COD_OCUP_PADRE FAMI_TRABAJOLABORPADRE 
,FAMI_COD_OCUP_MADRE FAMI_TRABAJOLABORMADRE --30
,ESTU_ESTRATO FAMI_ESTRATOVIVIENDA
,'' ESTU_OTROCOLE_TERMINO
,'' FAMI_TIENEINTERNET
,'' FAMI_TIENECOMPUTADOR
,'' FAMI_TIENELAVADORA  --35
,'' FAMI_TIENEHORNOMICROOGAS
,'' FAMI_TIENESERVICIOTV
,'' FAMI_TIENEAUTOMOVIL
,'' FAMI_TIENEMOTOCICLETA 
,'' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,'' ESTU_HORASSEMANATRABAJA 
,INST_COD_INSTITUCION INST_COD_INSTITUCION --45
,INST_NOMBRE_INSTITUCION INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,DIPO_CODIGOMUNICIPIO ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,ESTU_NIVEL_PRGM_ACADEMICO
,ESTU_METODO_PRGM 
,ESTU_NUCLEO_PREGRADO --55
,DIPO_CODIGOMUNICIPIO ESTU_INST_CODMUNICIPIO
,'' ESTU_INST_MUNICIPIO
,'' ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN_COD AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,ESTU_EXAM_CODMPIO_PRESENTACION ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,LEFT(ESTU_EXAM_CODMPIO_PRESENTACION,2 ) ESTU_COD_DEPTO_PRESENTACION --65
,NULL MOD_RAZONA_CUANTITAT_PUNT
,NULL MOD_RAZONA_CUANTITAT_DESEM
,NULL MOD_RAZONA_CUANTITATIVO_PNAL
,NULL MOD_RAZONA_CUANTITATIVO_PNBC
,MOD_COMP_LECT_PUNT MOD_LECTURA_CRITICA_PUNT --70
,MOD_COMP_LECT_DESEM MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
,NULL MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
,MOD_INGLES_PUNT
,MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,NULL MOD_COMUNI_ESCRITA_PUNT
,NULL MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_2006`
 LIMIT 3
),
SBPRO_2007 AS (
  SELECT
EVAL_TIPODOCUMENTO ESTU_TIPODOCUMENTO,
'' ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
ESTU_NACIMIENTO_DIA || '/'|| ESTU_NACIMIENTO_MES || '/'|| CAST(ESTU_NACIMIENTO_ANNO AS STRING) ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
PRUEBA AS PERIODO,
ESTU_CONSECUTIVO,
'' ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
ESTU_RESIDE_DEPT ESTU_DEPTO_RESIDE  -- 10 COLUMN
,LEFT(ESTU_RESIDE_CODMPIO, 2) ESTU_COD_RESIDE_DEPTO,
ESTU_RESIDE_MPIO ESTU_MCPIO_RESIDE,
ESTU_RESIDE_CODMPIO ESTU_COD_RESIDE_MCPIO
,CASE WHEN ECON_AREAVIVE =1 THEN 'Cabecera municipal'
      WHEN ECON_AREAVIVE =2 THEN 'Area rural' else null end ESTU_AREARESIDE  
,'' ESTU_COLE_TERMINO             -- 15 COLUMN
,NULL ESTU_CODDANE_COLE_TERMINO 
,'' ESTU_COD_COLE_MCPIO_TERMINO
,'' ESTU_TITULOOBTENIDOBACHILLER 
,'' ESTU_VALORMATRICULAUNIVERSIDAD  
,'' ESTU_PAGOMATRICULABECA          -- 20 COLUMN
,'' ESTU_PAGOMATRICULACREDITO
,'' ESTU_PAGOMATRICULAPADRES
,'' ESTU_PAGOMATRICULAPROPIO
,'' ESTU_COMOCAPACITOEXAMENSB11     
,'' ESTU_TIPODOCUMENTOSB11          -- 25
,ESTU_SEMESTRE_CURSANDO ESTU_SEMESTRECURSA
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_PADRE as numeric)) FAMI_EDUCACIONPADRE 
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_MADRE as numeric))  FAMI_EDUCACIONMADRE
,FAMI_COD_OCUP_PADRE FAMI_TRABAJOLABORPADRE 
,FAMI_COD_OCUP_MADRE FAMI_TRABAJOLABORMADRE --30
,ESTU_ESTRATO FAMI_ESTRATOVIVIENDA
,'' ESTU_OTROCOLE_TERMINO
,'' FAMI_TIENEINTERNET
,'' FAMI_TIENECOMPUTADOR
,'' FAMI_TIENELAVADORA  --35
,'' FAMI_TIENEHORNOMICROOGAS
,'' FAMI_TIENESERVICIOTV
,'' FAMI_TIENEAUTOMOVIL
,'' FAMI_TIENEMOTOCICLETA 
,'' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,'' ESTU_HORASSEMANATRABAJA 
,INST_COD_INSTITUCION INST_COD_INSTITUCION --45
,INST_NOMBRE_INSTITUCION INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,DIPO_CODIGOMUNICIPIO ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,ESTU_NIVEL_PRGM_ACADEMICO
,ESTU_METODO_PRGM 
,ESTU_NUCLEO_PREGRADO --55
,DIPO_CODIGOMUNICIPIO ESTU_INST_CODMUNICIPIO
,'' ESTU_INST_MUNICIPIO
,'' ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN_COD AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,ESTU_EXAM_CODMPIO_PRESENTACION ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,LEFT(ESTU_EXAM_CODMPIO_PRESENTACION,2 ) ESTU_COD_DEPTO_PRESENTACION --65
,NULL MOD_RAZONA_CUANTITAT_PUNT
,NULL MOD_RAZONA_CUANTITAT_DESEM
,NULL MOD_RAZONA_CUANTITATIVO_PNAL
,NULL MOD_RAZONA_CUANTITATIVO_PNBC
,MOD_COMP_LECT_PUNT MOD_LECTURA_CRITICA_PUNT --70
,MOD_COMP_LECT_DESEM MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
,NULL MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
,MOD_INGLES_PUNT
,MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,NULL MOD_COMUNI_ESCRITA_PUNT
,NULL MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_2007`
 LIMIT 3
),

SBPRO_20081 AS (
  SELECT
EVAL_TIPODOCUMENTO ESTU_TIPODOCUMENTO,
'' ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
ESTU_NACIMIENTO_DIA || '/'|| ESTU_NACIMIENTO_MES || '/'|| CAST(ESTU_NACIMIENTO_ANNO AS STRING) ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
PRUEBA AS PERIODO,
ESTU_CONSECUTIVO,
'' ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
ESTU_RESIDE_DEPT ESTU_DEPTO_RESIDE  -- 10 COLUMN
,LEFT(ESTU_RESIDE_CODMPIO, 2) ESTU_COD_RESIDE_DEPTO,
ESTU_RESIDE_MPIO ESTU_MCPIO_RESIDE,
ESTU_RESIDE_CODMPIO ESTU_COD_RESIDE_MCPIO
,CASE WHEN ECON_AREAVIVE =1 THEN 'Cabecera municipal'
      WHEN ECON_AREAVIVE =2 THEN 'Area rural' else null end ESTU_AREARESIDE  
,'' ESTU_COLE_TERMINO             -- 15 COLUMN
,NULL ESTU_CODDANE_COLE_TERMINO 
,'' ESTU_COD_COLE_MCPIO_TERMINO
,'' ESTU_TITULOOBTENIDOBACHILLER 
,'' ESTU_VALORMATRICULAUNIVERSIDAD  
,'' ESTU_PAGOMATRICULABECA          -- 20 COLUMN
,'' ESTU_PAGOMATRICULACREDITO
,'' ESTU_PAGOMATRICULAPADRES
,'' ESTU_PAGOMATRICULAPROPIO
,'' ESTU_COMOCAPACITOEXAMENSB11     
,'' ESTU_TIPODOCUMENTOSB11          -- 25
,ESTU_SEMESTRE_CURSANDO ESTU_SEMESTRECURSA
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_PADRE as numeric)) FAMI_EDUCACIONPADRE 
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_MADRE as numeric))  FAMI_EDUCACIONMADRE
,FAMI_COD_OCUP_PADRE FAMI_TRABAJOLABORPADRE 
,CAST(FAMI_COD_OCUP_MADRE AS STRING) FAMI_TRABAJOLABORMADRE --30
,ESTU_ESTRATO FAMI_ESTRATOVIVIENDA
,'' ESTU_OTROCOLE_TERMINO
,'' FAMI_TIENEINTERNET
,'' FAMI_TIENECOMPUTADOR
,'' FAMI_TIENELAVADORA  --35
,'' FAMI_TIENEHORNOMICROOGAS
,'' FAMI_TIENESERVICIOTV
,'' FAMI_TIENEAUTOMOVIL
,'' FAMI_TIENEMOTOCICLETA 
,'' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,'' ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,INST_NOMBRE_INSTITUCION INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,DIPO_CODIGOMUNICIPIO ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,ESTU_NIVEL_PRGM_ACADEMICO
,ESTU_METODO_PRGM 
,ESTU_NUCLEO_PREGRADO --55
,DIPO_CODIGOMUNICIPIO ESTU_INST_CODMUNICIPIO
,'' ESTU_INST_MUNICIPIO
,'' ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN_COD AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,DIPO_CODIGOMUNICIPIO ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,LEFT(DIPO_CODIGOMUNICIPIO,2 ) ESTU_COD_DEPTO_PRESENTACION --65
,NULL MOD_RAZONA_CUANTITAT_PUNT
,NULL MOD_RAZONA_CUANTITAT_DESEM
,NULL MOD_RAZONA_CUANTITATIVO_PNAL
,NULL MOD_RAZONA_CUANTITATIVO_PNBC
,MOD_COMP_LECT_PUNT MOD_LECTURA_CRITICA_PUNT --70
,MOD_COMP_LECT_DESEM MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
,NULL MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
,MOD_INGLES_PUNT
,MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,NULL MOD_COMUNI_ESCRITA_PUNT
,NULL MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20081`
 LIMIT 3
),

SBPRO_20082 AS (
  SELECT
EVAL_TIPODOCUMENTO ESTU_TIPODOCUMENTO,
'' ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
ESTU_NACIMIENTO_DIA || '/'|| ESTU_NACIMIENTO_MES || '/'|| CAST(ESTU_NACIMIENTO_ANNO AS STRING) ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
PRUEBA AS PERIODO,
ESTU_CONSECUTIVO,
'' ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
ESTU_RESIDE_DEPT ESTU_DEPTO_RESIDE  -- 10 COLUMN
,LEFT(ESTU_RESIDE_CODMPIO, 2) ESTU_COD_RESIDE_DEPTO,
ESTU_RESIDE_MPIO ESTU_MCPIO_RESIDE,
ESTU_RESIDE_CODMPIO ESTU_COD_RESIDE_MCPIO
,CASE WHEN ECON_AREAVIVE =1 THEN 'Cabecera municipal'
      WHEN ECON_AREAVIVE =2 THEN 'Area rural' else null end ESTU_AREARESIDE  
,'' ESTU_COLE_TERMINO             -- 15 COLUMN
,NULL ESTU_CODDANE_COLE_TERMINO 
,'' ESTU_COD_COLE_MCPIO_TERMINO
,'' ESTU_TITULOOBTENIDOBACHILLER 
,'' ESTU_VALORMATRICULAUNIVERSIDAD  
,'' ESTU_PAGOMATRICULABECA          -- 20 COLUMN
,'' ESTU_PAGOMATRICULACREDITO
,'' ESTU_PAGOMATRICULAPADRES
,'' ESTU_PAGOMATRICULAPROPIO
,'' ESTU_COMOCAPACITOEXAMENSB11     
,'' ESTU_TIPODOCUMENTOSB11          -- 25
,ESTU_SEMESTRE_CURSANDO ESTU_SEMESTRECURSA
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_PADRE as numeric)) FAMI_EDUCACIONPADRE 
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_MADRE as numeric))  FAMI_EDUCACIONMADRE
,CAST(FAMI_COD_OCUP_PADRE AS STRING) FAMI_TRABAJOLABORPADRE 
,CAST(FAMI_COD_OCUP_MADRE AS STRING) FAMI_TRABAJOLABORMADRE --30
,ESTU_ESTRATO FAMI_ESTRATOVIVIENDA
,'' ESTU_OTROCOLE_TERMINO
,'' FAMI_TIENEINTERNET
,'' FAMI_TIENECOMPUTADOR
,'' FAMI_TIENELAVADORA  --35
,'' FAMI_TIENEHORNOMICROOGAS
,'' FAMI_TIENESERVICIOTV
,'' FAMI_TIENEAUTOMOVIL
,'' FAMI_TIENEMOTOCICLETA 
,'' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,'' ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,INST_NOMBRE_INSTITUCION INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,DIPO_CODIGOMUNICIPIO ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,ESTU_NIVEL_PRGM_ACADEMICO
,ESTU_METODO_PRGM 
,ESTU_NUCLEO_PREGRADO --55
,DIPO_CODIGOMUNICIPIO ESTU_INST_CODMUNICIPIO
,'' ESTU_INST_MUNICIPIO
,'' ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN_COD AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,DIPO_CODIGOMUNICIPIO ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,LEFT(DIPO_CODIGOMUNICIPIO,2 ) ESTU_COD_DEPTO_PRESENTACION --65
,NULL MOD_RAZONA_CUANTITAT_PUNT
,NULL MOD_RAZONA_CUANTITAT_DESEM
,NULL MOD_RAZONA_CUANTITATIVO_PNAL
,NULL MOD_RAZONA_CUANTITATIVO_PNBC
,MOD_COMP_LECT_PUNT MOD_LECTURA_CRITICA_PUNT --70
,MOD_COMP_LECT_DESEM MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
,NULL MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
,MOD_INGLES_PUNT
,MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,NULL MOD_COMUNI_ESCRITA_PUNT
,NULL MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20082`
 LIMIT 3
),

SBPRO_2009 AS (
  SELECT
EVAL_TIPODOCUMENTO ESTU_TIPODOCUMENTO,
'' ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
ESTU_NACIMIENTO_DIA || '/'|| ESTU_NACIMIENTO_MES || '/'|| CAST(ESTU_NACIMIENTO_ANNO AS STRING) ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
PRUEBA AS PERIODO,
FTP_CONSECUTIVO ESTU_CONSECUTIVO,
'' ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
ESTU_RESIDE_DEPT ESTU_DEPTO_RESIDE  -- 10 COLUMN
,LEFT(ESTU_RESIDE_CODMPIO, 2) ESTU_COD_RESIDE_DEPTO,
ESTU_RESIDE_MPIO ESTU_MCPIO_RESIDE,
ESTU_RESIDE_CODMPIO ESTU_COD_RESIDE_MCPIO
,CASE WHEN ECON_AREAVIVE =1 THEN 'Cabecera municipal'
      WHEN ECON_AREAVIVE =2 THEN 'Area rural' else null end ESTU_AREARESIDE  
,'' ESTU_COLE_TERMINO             -- 15 COLUMN
,NULL ESTU_CODDANE_COLE_TERMINO 
,'' ESTU_COD_COLE_MCPIO_TERMINO
,'' ESTU_TITULOOBTENIDOBACHILLER 
,'' ESTU_VALORMATRICULAUNIVERSIDAD  
,'' ESTU_PAGOMATRICULABECA          -- 20 COLUMN
,'' ESTU_PAGOMATRICULACREDITO
,'' ESTU_PAGOMATRICULAPADRES
,'' ESTU_PAGOMATRICULAPROPIO
,'' ESTU_COMOCAPACITOEXAMENSB11     
,'' ESTU_TIPODOCUMENTOSB11          -- 25
,ESTU_SEMESTRE_CURSANDO ESTU_SEMESTRECURSA
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_PADRE as numeric)) FAMI_EDUCACIONPADRE 
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_MADRE as numeric))  FAMI_EDUCACIONMADRE
,CAST(FAMI_COD_OCUP_PADRE AS STRING) FAMI_TRABAJOLABORPADRE 
,CAST(FAMI_COD_OCUP_MADRE AS STRING) FAMI_TRABAJOLABORMADRE --30
,ESTU_ESTRATO FAMI_ESTRATOVIVIENDA
,'' ESTU_OTROCOLE_TERMINO
,CAST(ECON_SN_INTERNET AS STRING) FAMI_TIENEINTERNET
,CAST(ECON_SN_COMPUTADOR AS STRING) FAMI_TIENECOMPUTADOR
,CAST(ECON_SN_COMPUTADOR AS STRING)  FAMI_TIENELAVADORA  --35
,CAST(ECON_SN_MICROONDAS AS STRING) FAMI_TIENEHORNOMICROOGAS
,CAST( ECON_SN_SERVICIO_TV AS STRING)  FAMI_TIENESERVICIOTV
,CAST(ECON_SN_AUTOMOVIL AS STRING)  FAMI_TIENEAUTOMOVIL
,'' FAMI_TIENEMOTOCICLETA 
,'' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORAS_TRABAJO AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,INST_PERTENECE_EVALUADO  INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
,'' ESTU_INST_CODMUNICIPIO
,'' ESTU_INST_MUNICIPIO
,'' ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN_COD AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,ESTU_EXAM_CODMPIO_PRESENTACION ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,LEFT(ESTU_EXAM_CODMPIO_PRESENTACION,2 ) ESTU_COD_DEPTO_PRESENTACION --65
,NULL MOD_RAZONA_CUANTITAT_PUNT
,NULL MOD_RAZONA_CUANTITAT_DESEM
,NULL MOD_RAZONA_CUANTITATIVO_PNAL
,NULL MOD_RAZONA_CUANTITATIVO_PNBC
,COMP_COMPREN_LECTORA_PUNT MOD_LECTURA_CRITICA_PUNT --70
,COMP_COMPREN_LECTORA_DESEM MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
,NULL MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
,COMP_INGLES_PUNT MOD_INGLES_PUNT
,COMP_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,NULL MOD_COMUNI_ESCRITA_PUNT
,NULL MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_2009`
 LIMIT 3
),
SBPRO_2010 AS (
  SELECT
EVAL_TIPODOCUMENTO ESTU_TIPODOCUMENTO,
'' ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
ESTU_NACIMIENTO_DIA || '/'|| ESTU_NACIMIENTO_MES || '/'|| CAST(ESTU_NACIMIENTO_ANNO AS STRING) ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
PRUEBA AS PERIODO,
FTP_CONSECUTIVO ESTU_CONSECUTIVO,
'' ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
ESTU_RESIDE_DEPT ESTU_DEPTO_RESIDE  -- 10 COLUMN
,LEFT(ESTU_RESIDE_CODMPIO, 2) ESTU_COD_RESIDE_DEPTO,
ESTU_RESIDE_MPIO ESTU_MCPIO_RESIDE,
ESTU_RESIDE_CODMPIO ESTU_COD_RESIDE_MCPIO
,CASE WHEN ECON_AREAVIVE =1 THEN 'Cabecera municipal'
      WHEN ECON_AREAVIVE =2 THEN 'Area rural' else null end ESTU_AREARESIDE  
,'' ESTU_COLE_TERMINO             -- 15 COLUMN
,NULL ESTU_CODDANE_COLE_TERMINO 
,'' ESTU_COD_COLE_MCPIO_TERMINO
,'' ESTU_TITULOOBTENIDOBACHILLER 
,'' ESTU_VALORMATRICULAUNIVERSIDAD  
,'' ESTU_PAGOMATRICULABECA          -- 20 COLUMN
,'' ESTU_PAGOMATRICULACREDITO
,'' ESTU_PAGOMATRICULAPADRES
,'' ESTU_PAGOMATRICULAPROPIO
,'' ESTU_COMOCAPACITOEXAMENSB11     
,'' ESTU_TIPODOCUMENTOSB11          -- 25
,ESTU_SEMESTRE_CURSANDO ESTU_SEMESTRECURSA
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_PADRE as numeric)) FAMI_EDUCACIONPADRE 
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_MADRE as numeric))  FAMI_EDUCACIONMADRE
,CAST(FAMI_COD_OCUP_PADRE AS STRING) FAMI_TRABAJOLABORPADRE 
,CAST(FAMI_COD_OCUP_MADRE AS STRING) FAMI_TRABAJOLABORMADRE --30
,ESTU_ESTRATO FAMI_ESTRATOVIVIENDA
,'' ESTU_OTROCOLE_TERMINO
,CAST(ECON_SN_INTERNET AS STRING) FAMI_TIENEINTERNET
,CAST(ECON_SN_COMPUTADOR AS STRING) FAMI_TIENECOMPUTADOR
,CAST(ECON_SN_COMPUTADOR AS STRING)  FAMI_TIENELAVADORA  --35
,CAST(ECON_SN_MICROONDAS AS STRING) FAMI_TIENEHORNOMICROOGAS
,CAST( ECON_SN_SERVICIO_TV AS STRING)  FAMI_TIENESERVICIOTV
,CAST(ECON_SN_AUTOMOVIL AS STRING)  FAMI_TIENEAUTOMOVIL
,'' FAMI_TIENEMOTOCICLETA 
,'' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORAS_TRABAJO AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,INST_PERTENECE_EVALUADO  INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
,'' ESTU_INST_CODMUNICIPIO
,'' ESTU_INST_MUNICIPIO
,'' ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN_COD AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,ESTU_EXAM_CODMPIO_PRESENTACION ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,LEFT(ESTU_EXAM_CODMPIO_PRESENTACION,2 ) ESTU_COD_DEPTO_PRESENTACION --65
,NULL MOD_RAZONA_CUANTITAT_PUNT
,NULL MOD_RAZONA_CUANTITAT_DESEM
,NULL MOD_RAZONA_CUANTITATIVO_PNAL
,NULL MOD_RAZONA_CUANTITATIVO_PNBC
,COMP_COMPREN_LECTORA_PUNT MOD_LECTURA_CRITICA_PUNT --70
,COMP_COMPREN_LECTORA_DESEM MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
,NULL MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
,COMP_INGLES_PUNT MOD_INGLES_PUNT
,COMP_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,NULL MOD_COMUNI_ESCRITA_PUNT
,NULL MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_2010`
 LIMIT 3
),


SBPRO_20111 AS (
  SELECT
EVAL_TIPODOCUMENTO ESTU_TIPODOCUMENTO,
'' ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
ESTU_NACIMIENTO_DIA || '/'|| ESTU_NACIMIENTO_MES || '/'|| CAST(ESTU_NACIMIENTO_ANNO AS STRING) ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
PRUEBA AS PERIODO,
FTP_CONSECUTIVO ESTU_CONSECUTIVO,
'' ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
ESTU_RESIDE_DEPT ESTU_DEPTO_RESIDE  -- 10 COLUMN
,LEFT(ESTU_RESIDE_CODMPIO, 2) ESTU_COD_RESIDE_DEPTO,
ESTU_RESIDE_MPIO ESTU_MCPIO_RESIDE,
ESTU_RESIDE_CODMPIO ESTU_COD_RESIDE_MCPIO
,CASE WHEN ECON_AREAVIVE =1 THEN 'Cabecera municipal'
      WHEN ECON_AREAVIVE =2 THEN 'Area rural' else null end ESTU_AREARESIDE  
,'' ESTU_COLE_TERMINO             -- 15 COLUMN
,NULL ESTU_CODDANE_COLE_TERMINO 
,'' ESTU_COD_COLE_MCPIO_TERMINO
,'' ESTU_TITULOOBTENIDOBACHILLER 
,'' ESTU_VALORMATRICULAUNIVERSIDAD  
,'' ESTU_PAGOMATRICULABECA          -- 20 COLUMN
,'' ESTU_PAGOMATRICULACREDITO
,'' ESTU_PAGOMATRICULAPADRES
,'' ESTU_PAGOMATRICULAPROPIO
,'' ESTU_COMOCAPACITOEXAMENSB11     
,'' ESTU_TIPODOCUMENTOSB11          -- 25
,ESTU_SEMESTRE_CURSANDO ESTU_SEMESTRECURSA
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_PADRE as numeric)) FAMI_EDUCACIONPADRE 
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_MADRE as numeric))  FAMI_EDUCACIONMADRE
,CAST(FAMI_COD_OCUP_PADRE AS STRING) FAMI_TRABAJOLABORPADRE 
,CAST(FAMI_COD_OCUP_MADRE AS STRING) FAMI_TRABAJOLABORMADRE --30
,ESTU_ESTRATO FAMI_ESTRATOVIVIENDA
,'' ESTU_OTROCOLE_TERMINO
,CAST(ECON_SN_INTERNET AS STRING) FAMI_TIENEINTERNET
,CAST(ECON_SN_COMPUTADOR AS STRING) FAMI_TIENECOMPUTADOR
,CAST(ECON_SN_COMPUTADOR AS STRING)  FAMI_TIENELAVADORA  --35
,CAST(ECON_SN_MICROONDAS AS STRING) FAMI_TIENEHORNOMICROOGAS
,CAST( ECON_SN_SERVICIO_TV AS STRING)  FAMI_TIENESERVICIOTV
,CAST(ECON_SN_AUTOMOVIL AS STRING)  FAMI_TIENEAUTOMOVIL
,'' FAMI_TIENEMOTOCICLETA 
,'' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORAS_TRABAJO AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,INST_PERTENECE_EVALUADO  INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
,'' ESTU_INST_CODMUNICIPIO
,'' ESTU_INST_MUNICIPIO
,'' ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN_COD AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,ESTU_EXAM_CODMPIO_PRESENTACION ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,LEFT(ESTU_EXAM_CODMPIO_PRESENTACION,2 ) ESTU_COD_DEPTO_PRESENTACION --65
,NULL MOD_RAZONA_CUANTITAT_PUNT
,NULL MOD_RAZONA_CUANTITAT_DESEM
,NULL MOD_RAZONA_CUANTITATIVO_PNAL
,NULL MOD_RAZONA_CUANTITATIVO_PNBC
,COMP_COMPREN_LECTORA_PUNT MOD_LECTURA_CRITICA_PUNT --70
,COMP_COMPREN_LECTORA_DESEM MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
,NULL MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
,COMP_INGLES_PUNT MOD_INGLES_PUNT
,COMP_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,NULL MOD_COMUNI_ESCRITA_PUNT
,NULL MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20111`
 LIMIT 3
),


SBPRO_20112 AS (
  SELECT
EVAL_TIPODOCUMENTO ESTU_TIPODOCUMENTO,
'' ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
ESTU_NACIMIENTO_DIA || '/'|| ESTU_NACIMIENTO_MES || '/'|| CAST(ESTU_NACIMIENTO_ANNO AS STRING) ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
PRUEBA AS PERIODO,
FTP_CONSECUTIVO ESTU_CONSECUTIVO,
'' ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
ESTU_RESIDE_DEPT ESTU_DEPTO_RESIDE  -- 10 COLUMN
,LEFT(ESTU_RESIDE_CODMPIO, 2) ESTU_COD_RESIDE_DEPTO,
ESTU_RESIDE_MPIO ESTU_MCPIO_RESIDE,
ESTU_RESIDE_CODMPIO ESTU_COD_RESIDE_MCPIO
,CASE WHEN ECON_AREAVIVE =1 THEN 'Cabecera municipal'
      WHEN ECON_AREAVIVE =2 THEN 'Area rural' else null end ESTU_AREARESIDE  
,'' ESTU_COLE_TERMINO             -- 15 COLUMN
,NULL ESTU_CODDANE_COLE_TERMINO 
,'' ESTU_COD_COLE_MCPIO_TERMINO
,'' ESTU_TITULOOBTENIDOBACHILLER 
,'' ESTU_VALORMATRICULAUNIVERSIDAD  
,'' ESTU_PAGOMATRICULABECA          -- 20 COLUMN
,'' ESTU_PAGOMATRICULACREDITO
,'' ESTU_PAGOMATRICULAPADRES
,'' ESTU_PAGOMATRICULAPROPIO
,'' ESTU_COMOCAPACITOEXAMENSB11     
,'' ESTU_TIPODOCUMENTOSB11          -- 25
,ESTU_SEMESTRE_CURSANDO ESTU_SEMESTRECURSA
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_PADRE as numeric)) FAMI_EDUCACIONPADRE 
,`ph-jabri.udfs.education_level_from_numeric`( cast(FAMI_COD_EDUCA_MADRE as numeric))  FAMI_EDUCACIONMADRE
,CAST(FAMI_COD_OCUP_PADRE AS STRING) FAMI_TRABAJOLABORPADRE 
,CAST(FAMI_COD_OCUP_MADRE AS STRING) FAMI_TRABAJOLABORMADRE --30
,ESTU_ESTRATO FAMI_ESTRATOVIVIENDA
,'' ESTU_OTROCOLE_TERMINO
,CAST(ECON_SN_INTERNET AS STRING) FAMI_TIENEINTERNET
,CAST(ECON_SN_COMPUTADOR AS STRING) FAMI_TIENECOMPUTADOR
,CAST(ECON_SN_COMPUTADOR AS STRING)  FAMI_TIENELAVADORA  --35
,CAST(ECON_SN_MICROONDAS AS STRING) FAMI_TIENEHORNOMICROOGAS
,CAST( ECON_SN_SERVICIO_TV AS STRING)  FAMI_TIENESERVICIOTV
,CAST(ECON_SN_AUTOMOVIL AS STRING)  FAMI_TIENEAUTOMOVIL
,'' FAMI_TIENEMOTOCICLETA 
,'' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORAS_TRABAJO AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,INST_PERTENECE_EVALUADO  INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
,'' ESTU_INST_CODMUNICIPIO
,'' ESTU_INST_MUNICIPIO
,'' ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN_COD AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,ESTU_EXAM_CODMPIO_PRESENTACION ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,LEFT(ESTU_EXAM_CODMPIO_PRESENTACION,2 ) ESTU_COD_DEPTO_PRESENTACION --65
,NULL MOD_RAZONA_CUANTITAT_PUNT
,NULL MOD_RAZONA_CUANTITAT_DESEM
,NULL MOD_RAZONA_CUANTITATIVO_PNAL
,NULL MOD_RAZONA_CUANTITATIVO_PNBC
,MOD_LECTURA_CRITICA MOD_LECTURA_CRITICA_PUNT --70
,'' MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
,NULL MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
,MOD_INGLES_PUNT MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,MOD_COMUNICA_ESCRITA_PUNT MOD_COMUNI_ESCRITA_PUNT
,MOD_COMUNICA_ESCRITA_DESEM MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20112`  
 LIMIT 3
), 

SBPRO_20121 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
ESTU_SEMESTRECURSA ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENE_MICROONDAS FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENE_SERVICIOTV FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  '' FAMI_TIENEMOTOCICLETA, 
 '' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,   INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
, NULL MOD_RAZONA_CUANTITAT_DESEM
, NULL MOD_RAZONA_CUANTITATIVO_PNAL
, NULL MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
,'' MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20121` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),
SBPRO_20122 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
20122.0 PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
ESTU_SEMESTRECURSA ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENE_MICROONDAS FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENE_SERVICIOTV FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  '' FAMI_TIENEMOTOCICLETA, 
 '' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,   INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
, NULL MOD_RAZONA_CUANTITAT_DESEM
, NULL MOD_RAZONA_CUANTITATIVO_PNAL
, NULL MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
,'' MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20122` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),
SBPRO_20132 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
ESTU_SEMESTRECURSA ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENE_MICROONDAS FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENE_SERVICIOTV FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  '' FAMI_TIENEMOTOCICLETA, 
 '' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,   INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
, NULL MOD_RAZONA_CUANTITAT_DESEM
, NULL MOD_RAZONA_CUANTITATIVO_PNAL
, NULL MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
,'' MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20132` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),
SBPRO_20131 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
ESTU_SEMESTRECURSA ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENE_MICROONDAS FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENE_SERVICIOTV FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  '' FAMI_TIENEMOTOCICLETA, 
 '' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,   INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
, NULL MOD_RAZONA_CUANTITAT_DESEM
, NULL MOD_RAZONA_CUANTITATIVO_PNAL
, NULL MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
,'' MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20131` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),
SBPRO_20141 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
ESTU_SEMESTRECURSA ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENE_MICROONDAS FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENE_SERVICIOTV FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  '' FAMI_TIENEMOTOCICLETA, 
 '' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,   INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
, NULL MOD_RAZONA_CUANTITAT_DESEM
, NULL MOD_RAZONA_CUANTITATIVO_PNAL
, NULL MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
,'' MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20141` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),
SBPRO_20142 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
ESTU_SEMESTRECURSA ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENE_MICROONDAS FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENE_SERVICIOTV FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  '' FAMI_TIENEMOTOCICLETA, 
 '' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,   INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
, NULL MOD_RAZONA_CUANTITAT_DESEM
, NULL MOD_RAZONA_CUANTITATIVO_PNAL
, NULL MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
,'' MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20142` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),
 
SBPRO_20151 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
ESTU_SEMESTRECURSA ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENE_MICROONDAS FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENE_SERVICIOTV FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  '' FAMI_TIENEMOTOCICLETA, 
 '' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,   INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
, NULL MOD_RAZONA_CUANTITAT_DESEM
, NULL MOD_RAZONA_CUANTITATIVO_PNAL
, NULL MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
,'' MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20151` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),

SBPRO_20152 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
ESTU_SEMESTRECURSA ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  '' FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENE_MICROONDAS FAMI_TIENEHORNOMICROOGAS,
  '' FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  '' FAMI_TIENEMOTOCICLETA, 
 '' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,   INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
, NULL MOD_RAZONA_CUANTITAT_DESEM
, NULL MOD_RAZONA_CUANTITATIVO_PNAL
, NULL MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
,'' MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20152` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),

SBPRO_2016 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
ESTU_SEMESTRECURSA ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
   FAMI_TIENEHORNOMICROOGAS,
   FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  FAMI_TIENEMOTOCICLETA, 
 '' FAMI_TIENECONSOLAVIDEOJUEGOS --40
,'' FAMI_CUANTOSCOMPARTEBA_O
,'' ESTU_PRESENTACIONCASA
,'' ESTU_PAISDOCUMENTOS11
,CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA 
,CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION --45
,   INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,NULL ESTU_SNIES_PRGMACADEMICO
,'' GRUPOREFERENCIA 
,'' ESTU_PRGM_CODMUNICIPIO --50 
,'' ESTU_PRGM_MUNICIPIO
,'' ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
,'PRESENCIAL' ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
,'' ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
,'' ESTU_MCPIO_PRESENTACION
,'' ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
, NULL MOD_RAZONA_CUANTITAT_DESEM
, NULL MOD_RAZONA_CUANTITATIVO_PNAL
, NULL MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
,'' MOD_LECTURA_CRITICA_DESEM
,NULL MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
,NULL MOD_COMPETEN_CIUDADA_DESEM --75
,NULL MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
,NULL MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
,NULL MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
,NULL PUNT_GLOBAL
,NULL PERCENTIL_NBC
,NULL PERCENTIL_GLOBAL
,NULL ESTU_INSE_INDIVIDUAL
,'' ESTU_NSE_INDIVIDUAL --90
,NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_2016` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),

SBPRO_2017 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
ESTU_SEMESTRECURSA ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  '' FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  FAMI_TIENEMOTOCICLETA, 
 FAMI_TIENECONSOLAVIDEOJUEGOS,  --40
FAMI_CUANTOSCOMPARTEBA_O,
 '' ESTU_PRESENTACIONCASA,
 '' ESTU_PAISDOCUMENTOS11,
 CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA ,
 CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION, --45
 INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,  ESTU_SNIES_PRGMACADEMICO
, GRUPOREFERENCIA 
, ESTU_PRGM_CODMUNICIPIO --50 
, ESTU_PRGM_MUNICIPIO
, ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
, ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
, ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
, ESTU_MCPIO_PRESENTACION
, ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
,  MOD_RAZONA_CUANTITAT_DESEM
,  MOD_RAZONA_CUANTITATIVO_PNAL
, NULL MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
, CAST(MOD_LECTURA_CRITICA_DESEM AS STRING) MOD_LECTURA_CRITICA_DESEM
, MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
, MOD_COMPETEN_CIUDADA_DESEM --75
, MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
, MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
, MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
, PUNT_GLOBAL
,NULL PERCENTIL_NBC
, PERCENTIL_GLOBAL
, ESTU_INSE_INDIVIDUAL
, CAST(ESTU_NSE_INDIVIDUAL AS STRING) --90
, ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_2017` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),

SBPRO_2018 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
'' ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  '' FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  FAMI_TIENEMOTOCICLETA, 
 FAMI_TIENECONSOLAVIDEOJUEGOS,  --40
FAMI_CUANTOSCOMPARTEBA_O,
 '' ESTU_PRESENTACIONCASA,
 '' ESTU_PAISDOCUMENTOS11,
 CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA ,
 CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION, --45
 INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,  ESTU_SNIES_PRGMACADEMICO
, GRUPOREFERENCIA 
, ESTU_PRGM_CODMUNICIPIO --50 
, ESTU_PRGM_MUNICIPIO
, ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
, ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
, ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
, ESTU_MCPIO_PRESENTACION
, ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
,  MOD_RAZONA_CUANTITAT_DESEM
,  MOD_RAZONA_CUANTITATIVO_PNAL
, NULL MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
, CAST(MOD_LECTURA_CRITICA_DESEM AS STRING) MOD_LECTURA_CRITICA_DESEM
, MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
, MOD_COMPETEN_CIUDADA_DESEM --75
, MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
, MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
, MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
, PUNT_GLOBAL
,NULL PERCENTIL_NBC
, PERCENTIL_GLOBAL
, ESTU_INSE_INDIVIDUAL
, CAST(ESTU_NSE_INDIVIDUAL AS STRING) ESTU_NSE_INDIVIDUAL --90
, ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_2018` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),

SBPRO_2019 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
CAST(ESTU_COLE_TERMINO AS STRING)ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
'' ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
'' ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  '' FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  FAMI_TIENEMOTOCICLETA, 
 FAMI_TIENECONSOLAVIDEOJUEGOS,  --40
FAMI_CUANTOSCOMPARTEBA_O,
 '' ESTU_PRESENTACIONCASA,
 '' ESTU_PAISDOCUMENTOS11,
 CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA ,
 CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION, --45
 INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,  ESTU_SNIES_PRGMACADEMICO
, '' GRUPOREFERENCIA 
, ESTU_PRGM_CODMUNICIPIO --50 
, ESTU_PRGM_MUNICIPIO
, ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
, ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
, ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
, ESTU_MCPIO_PRESENTACION
, ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
,  MOD_RAZONA_CUANTITAT_DESEM
,  MOD_RAZONA_CUANTITATIVO_PNAL
, NULL MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
, CAST(MOD_LECTURA_CRITICA_DESEM AS STRING) MOD_LECTURA_CRITICA_DESEM
, MOD_LECTURA_CRITICA_PNAL
,NULL MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
, MOD_COMPETEN_CIUDADA_DESEM --75
, MOD_COMPETEN_CIUDADA_PNAL
,NULL MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
, MOD_INGLES_PNAL --80
,NULL MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
, MOD_COMUNI_ESCRITA_PNAL
,NULL MOD_COMUNI_ESCRITA_PNBC --85
, PUNT_GLOBAL
,NULL PERCENTIL_NBC
, PERCENTIL_GLOBAL
, ESTU_INSE_INDIVIDUAL
, CAST(ESTU_NSE_INDIVIDUAL AS STRING) ESTU_NSE_INDIVIDUAL --90
, ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_2019` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),

SBPRO_2020 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
'' ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
  ESTU_OTROCOLE_TERMINO,
  '' FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  FAMI_TIENEMOTOCICLETA, 
 FAMI_TIENECONSOLAVIDEOJUEGOS,  --40
FAMI_CUANTOSCOMPARTEBA_O,
 '' ESTU_PRESENTACIONCASA,
  '' ESTU_PAISDOCUMENTOS11,
 CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA ,
 CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION, --45
 INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,  ESTU_SNIES_PRGMACADEMICO
, GRUPOREFERENCIA 
, ESTU_PRGM_CODMUNICIPIO --50 
, ESTU_PRGM_MUNICIPIO
, ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
, ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
, ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
, ESTU_MCPIO_PRESENTACION
, ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
,  MOD_RAZONA_CUANTITAT_DESEM
,  MOD_RAZONA_CUANTITATIVO_PNAL
,  MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
, CAST(MOD_LECTURA_CRITICA_DESEM AS STRING) MOD_LECTURA_CRITICA_DESEM
, MOD_LECTURA_CRITICA_PNAL
, MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
, MOD_COMPETEN_CIUDADA_DESEM --75
, MOD_COMPETEN_CIUDADA_PNAL
, MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
, MOD_INGLES_PNAL --80
, MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
, MOD_COMUNI_ESCRITA_PNAL
, MOD_COMUNI_ESCRITA_PNBC --85
, PUNT_GLOBAL
, PERCENTIL_NBC
, PERCENTIL_GLOBAL
, ESTU_INSE_INDIVIDUAL
, CAST(ESTU_NSE_INDIVIDUAL AS STRING) ESTU_NSE_INDIVIDUAL --90
, ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_2020` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),

SBPRO_20221 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
'' ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
 ESTU_COLE_TERMINO ESTU_OTROCOLE_TERMINO,
  '' FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  FAMI_TIENEMOTOCICLETA, 
 FAMI_TIENECONSOLAVIDEOJUEGOS,  --40
`FAMI_CUANTOSCOMPARTEBAÑO` FAMI_CUANTOSCOMPARTEBA_O,
 '' ESTU_PRESENTACIONCASA,
  '' ESTU_PAISDOCUMENTOS11,
 CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA ,
 CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION, --45
 INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,  ESTU_SNIES_PRGMACADEMICO
, GRUPOREFERENCIA 
, ESTU_PRGM_CODMUNICIPIO --50 
, ESTU_PRGM_MUNICIPIO
, ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
, ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
, ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
, ESTU_MCPIO_PRESENTACION
, ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
,  MOD_RAZONA_CUANTITAT_DESEM
,  MOD_RAZONA_CUANTITATIVO_PNAL
,  MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
, CAST(MOD_LECTURA_CRITICA_DESEM AS STRING) MOD_LECTURA_CRITICA_DESEM
, MOD_LECTURA_CRITICA_PNAL
, MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
, MOD_COMPETEN_CIUDADA_DESEM --75
, MOD_COMPETEN_CIUDADA_PNAL
, MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
, MOD_INGLES_PNAL --80
, MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
, MOD_COMUNI_ESCRITA_PNAL
, MOD_COMUNI_ESCRITA_PNBC --85
, PUNT_GLOBAL
, PERCENTIL_NBC
, PERCENTIL_GLOBAL
, NULL ESTU_INSE_INDIVIDUAL
, '' STU_NSE_INDIVIDUAL --90
, NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20221` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),

SBPRO_20222 AS (
  SELECT
 ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO AS ESTU_GENERO,
 ESTU_FECHANACIMIENTO,
'' AS ESTU_EXTERIOR, -- 5 COLUMN
  PERIODO,
 ESTU_CONSECUTIVO,
 ESTU_ESTUDIANTE, 
ESTU_PAIS_RESIDE ,
 ESTU_DEPTO_RESIDE , -- 10 COLUMN
 ESTU_COD_RESIDE_DEPTO,
 ESTU_MCPIO_RESIDE,
 ESTU_COD_RESIDE_MCPIO,
'' ESTU_AREARESIDE  ,
ESTU_COLE_TERMINO,             -- 15 COLUMN
SAFE_CAST(ESTU_CODDANE_COLE_TERMINO AS NUMERIC) ESTU_CODDANE_COLE_TERMINO ,
SAFE_CAST(ESTU_COD_COLE_MCPIO_TERMINO AS STRING) ESTU_COD_COLE_MCPIO_TERMINO,
 ESTU_TITULOOBTENIDOBACHILLER, 
 ESTU_VALORMATRICULAUNIVERSIDAD,  
 ESTU_PAGOMATRICULABECA ,         -- 20 COLUMN
 ESTU_PAGOMATRICULACREDITO,
 ESTU_PAGOMATRICULAPADRES,
 ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,     
 ESTU_TIPODOCUMENTOSB11  ,        -- 25
'' ESTU_SEMESTRECURSA,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONPADRE)  FAMI_EDUCACIONPADRE,
-- `ph-jabri.udfs.categorize_education_level`(FAMI_EDUCACIONMADRE)  FAMI_EDUCACIONMADRE, 
  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE, 
  '' FAMI_TRABAJOLABORPADRE ,
  '' FAMI_TRABAJOLABORMADRE , --30
  SAFE_CAST(REPLACE(FAMI_ESTRATOVIVIENDA, 'Estrato ','') AS NUMERIC)  FAMI_ESTRATOVIVIENDA,
 ESTU_COLE_TERMINO ESTU_OTROCOLE_TERMINO,
  '' FAMI_TIENEINTERNET,
  FAMI_TIENECOMPUTADOR,
  FAMI_TIENELAVADORA,  --35
  FAMI_TIENEHORNOMICROOGAS,
  FAMI_TIENESERVICIOTV,
  FAMI_TIENEAUTOMOVIL,
  FAMI_TIENEMOTOCICLETA, 
 FAMI_TIENECONSOLAVIDEOJUEGOS,  --40
FAMI_CUANTOSCOMPARTEBA_O FAMI_CUANTOSCOMPARTEBA_O,
 '' ESTU_PRESENTACIONCASA,
  '' ESTU_PAISDOCUMENTOS11,
 CAST(ESTU_HORASSEMANATRABAJA AS STRING) ESTU_HORASSEMANATRABAJA ,
 CAST(INST_COD_INSTITUCION AS STRING) INST_COD_INSTITUCION, --45
 INST_NOMBRE_INSTITUCION
,ESTU_PRGM_ACADEMICO
,  ESTU_SNIES_PRGMACADEMICO
, GRUPOREFERENCIA 
, ESTU_PRGM_CODMUNICIPIO --50 
, ESTU_PRGM_MUNICIPIO
, ESTU_PRGM_DEPARTAMENTO
,INST_CARACTER_ACADEMICO ESTU_NIVEL_PRGM_ACADEMICO
, ESTU_METODO_PRGM 
,ESTU_PRGM_ACADEMICO ESTU_NUCLEO_PREGRADO --55
, ESTU_INST_CODMUNICIPIO
, ESTU_INST_MUNICIPIO
, ESTU_INST_DEPARTAMENTO
,INST_CARACTER_ACADEMICO 
,CAST(INST_ORIGEN AS STRING) INST_ORIGEN --60
, ESTU_PRIVADO_LIBERTAD
,  ESTU_COD_MCPIO_PRESENTACION
, ESTU_MCPIO_PRESENTACION
, ESTU_DEPTO_PRESENTACION 
,  ESTU_COD_DEPTO_PRESENTACION --65
,  MOD_RAZONA_CUANTITAT_PUNT
,  MOD_RAZONA_CUANTITAT_DESEM
,  MOD_RAZONA_CUANTITATIVO_PNAL
,  MOD_RAZONA_CUANTITATIVO_PNBC
, MOD_LECTURA_CRITICA_PUNT --70
, CAST(MOD_LECTURA_CRITICA_DESEM AS STRING) MOD_LECTURA_CRITICA_DESEM
, MOD_LECTURA_CRITICA_PNAL
, MOD_LECTURA_CRITICA_PNBC
, MOD_COMPETEN_CIUDADA_PUNT
, MOD_COMPETEN_CIUDADA_DESEM --75
, MOD_COMPETEN_CIUDADA_PNAL
, MOD_COMPETEN_CIUDADA_PNBC
, MOD_INGLES_PUNT
,MOD_INGLES_DESEM MOD_INGLES_DESEM
, MOD_INGLES_PNAL --80
, MOD_INGLES_PNBC
,  MOD_COMUNI_ESCRITA_PUNT
,  MOD_COMUNI_ESCRITA_DESEM
, MOD_COMUNI_ESCRITA_PNAL
, MOD_COMUNI_ESCRITA_PNBC --85
, PUNT_GLOBAL
, PERCENTIL_NBC
, PERCENTIL_GLOBAL
, NULL ESTU_INSE_INDIVIDUAL
, '' STU_NSE_INDIVIDUAL --90
, NULL ESTU_NSE_IES

 FROM `ph-jabri.SABER_PRO.SBPRO_20222` where ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 LIMIT 3
),
SB_UNIONES AS(
SELECT * , 2021 anio  FROM SBPRO_2021
UNION ALL 
SELECT * , 2006 anio  FROM SBPRO_2006
UNION ALL 
SELECT * , 2007 anio  FROM SBPRO_2007
UNION ALL 
SELECT * , 2008 anio  FROM SBPRO_20081
UNION ALL 
SELECT * , 2008 anio  FROM SBPRO_20082
UNION ALL 
SELECT * , 2009 anio  FROM SBPRO_2009
UNION ALL 
SELECT * , 2010 anio  FROM SBPRO_2010
UNION ALL 
SELECT * , 2011 anio  FROM SBPRO_20111
UNION ALL 
SELECT * , 2011 anio  FROM SBPRO_20112
UNION ALL 
SELECT * , 2012 anio  FROM SBPRO_20121
UNION ALL 
SELECT * , 2012 anio  FROM SBPRO_20122
UNION ALL 
SELECT * , 2013 anio  FROM SBPRO_20131
UNION ALL 
SELECT * , 2013 anio  FROM SBPRO_20132
UNION ALL 
SELECT * , 2014 anio  FROM SBPRO_20141 
UNION ALL 
SELECT * , 2014 anio  FROM SBPRO_20142
UNION ALL 
SELECT * , 2015 anio  FROM SBPRO_20151 
UNION ALL 
SELECT * , 2015 anio  FROM SBPRO_20152
UNION ALL 
SELECT * , 2016 anio  FROM SBPRO_2016 
UNION ALL 
SELECT * , 2017 anio  FROM SBPRO_2017
UNION ALL 
SELECT * , 2018 anio  FROM SBPRO_2018
UNION ALL 
SELECT * , 2019 anio  FROM SBPRO_2019
UNION ALL 
SELECT * , 2020 anio  FROM SBPRO_2020
UNION ALL 
SELECT * , 2022 anio  FROM SBPRO_20221
UNION ALL 
SELECT * , 2022 anio  FROM SBPRO_20222
)
SELECT
`ph-jabri.udfs.stem_1`(ESTU_NUCLEO_PREGRADO ) AS STEM_LEVEL_1, 
`ph-jabri.udfs.stem_2`(ESTU_NUCLEO_PREGRADO ) AS STEM_LEVEL_2, 
 * FROM SB_UNIONES
 ORDER BY anio
