CREATE OR REPLACE TABLE `ICFES.SBTyT_2016_2022`
OPTIONS () AS
WITH 
SBTyT_20161 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
ESTU_ESTADOCIVIL,
ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
ESTU_OTROCOLE_TERMINO,
ESTU_TITULOOBTENIDOBACHILLER,
ESTU_ANO_EXAMENESTADO_SB11, --20
ESTU_SEMESTRE_EXAMENESTADOSB11,
ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
CAST(ESTU_COMOCAPACITOEXAMENSB11 AS STRING) ESTU_COMOCAPACITOEXAMENSB11,
ESTU_TOMO_CURSOPREPARACION,
ESTU_CURSODOCENTESIES, --30
ESTU_CURSOIESAPOYOEXTERNO,
ESTU_CURSOIESEXTERNA,
ESTU_SIMULACROTIPOICFES,
ESTU_ACTIVIDADREFUERZOAREAS,
ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
ESTU_SEMESTRECURSA,
CAST(ESTU_ULTIMOGRADOAPROBO AS STRING ) AS ESTU_ULTIMOGRADOAPROBO,
ESTU_ANOTERMINOULTIMOGRADO,
ESTU_VECESPRESENTOEXAMEN, --40
FAMI_HOGARACTUAL,
FAMI_CABEZAFAMILIA,
FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_OCUPACIONPADRE,
FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
FAMI_NIVEL_SISBEN,
FAMI_PERSONASHOGAR, -- 50
FAMI_CUARTOSHOGAR,
FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
FAMI_INGRESO_FMILIAR_MENSUAL,
ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
ESTU_SNIES_PRGMACADEMICO,
GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
MOD_INGLES_PGREF,
MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
ESTU_INSE_INDIVIDUAL, -- 100
ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20161` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- -- LIMIT 5
), 
SBTyT_20162 AS (
 

SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
ESTU_ESTADOCIVIL,
ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
ESTU_OTROCOLE_TERMINO,
ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
ESTU_CURSODOCENTESIES, --30
ESTU_CURSOIESAPOYOEXTERNO,
ESTU_CURSOIESEXTERNA,
ESTU_SIMULACROTIPOICFES,
ESTU_ACTIVIDADREFUERZOAREAS,
ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
FAMI_HOGARACTUAL,
FAMI_CABEZAFAMILIA,
FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_OCUPACIONPADRE,
FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
FAMI_PERSONASHOGAR, -- 50
FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
ESTU_SNIES_PRGMACADEMICO,
GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
MOD_INGLES_PGREF,
MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
ESTU_INSE_INDIVIDUAL, -- 100
ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20162` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
),

SBTyT_20171 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
ESTU_ESTADOCIVIL,
ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
ESTU_OTROCOLE_TERMINO,
ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
ESTU_CURSODOCENTESIES, --30
ESTU_CURSOIESAPOYOEXTERNO,
ESTU_CURSOIESEXTERNA,
ESTU_SIMULACROTIPOICFES,
ESTU_ACTIVIDADREFUERZOAREAS,
ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
FAMI_HOGARACTUAL,
FAMI_CABEZAFAMILIA,
FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_OCUPACIONPADRE,
FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
FAMI_PERSONASHOGAR, -- 50
FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
'' FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
SAFE_CAST(ESTU_SNIES_PRGMACADEMICO AS NUMERIC) ESTU_SNIES_PRGMACADEMICO,
GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
SAFE_CAST(MOD_RAZONA_CUANTITATIVO_PGREF AS NUMERIC ) MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
SAFE_CAST(MOD_INGLES_PGREF AS NUMERIC ) MOD_INGLES_PGREF,
SAFE_CAST(MOD_COMUNI_ESCRITA_PUNT AS NUMERIC ) MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
ESTU_INSE_INDIVIDUAL, -- 100
ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20171` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
), 

SBTyT_20172 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
ESTU_TIENEETNIA ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
'' ESTU_ESTADOCIVIL,
ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
ESTU_OTROCOLE_TERMINO,
ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
ESTU_CURSODOCENTESIES, --30
ESTU_CURSOIESAPOYOEXTERNO,
ESTU_CURSOIESEXTERNA,
ESTU_SIMULACROTIPOICFES,
ESTU_ACTIVIDADREFUERZOAREAS,
ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
FAMI_HOGARACTUAL,
FAMI_CABEZAFAMILIA,
FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_OCUPACIONPADRE,
FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
FAMI_PERSONASHOGAR, -- 50
FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
'' FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
CAST(INST_COD_INSTITUCION AS NUMERIC) INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
SAFE_CAST(ESTU_SNIES_PRGMACADEMICO AS NUMERIC) ESTU_SNIES_PRGMACADEMICO,
GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
SAFE_CAST(MOD_RAZONA_CUANTITATIVO_PGREF AS NUMERIC ) MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
SAFE_CAST(MOD_INGLES_PGREF AS NUMERIC ) MOD_INGLES_PGREF,
SAFE_CAST(MOD_COMUNI_ESCRITA_PUNT AS NUMERIC ) MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
ESTU_INSE_INDIVIDUAL, -- 100
ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20172` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
), 

SBTyT_20181 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
ESTU_TIENEETNIA ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
'' ESTU_ESTADOCIVIL,
ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
ESTU_OTROCOLE_TERMINO,
ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
'' ESTU_CURSODOCENTESIES, --30
'' ESTU_CURSOIESAPOYOEXTERNO,
'' ESTU_CURSOIESEXTERNA,
ESTU_SIMULACROTIPOICFES,
ESTU_ACTIVIDADREFUERZOAREAS,
ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
FAMI_HOGARACTUAL,
FAMI_CABEZAFAMILIA,
FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_OCUPACIONPADRE,
FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
FAMI_PERSONASHOGAR, -- 50
FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
'' FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
CAST(INST_COD_INSTITUCION AS NUMERIC) INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
SAFE_CAST(ESTU_SNIES_PRGMACADEMICO AS NUMERIC) ESTU_SNIES_PRGMACADEMICO,
GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
SAFE_CAST(MOD_RAZONA_CUANTITATIVO_PGREF AS NUMERIC ) MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
SAFE_CAST(MOD_INGLES_PGREF AS NUMERIC ) MOD_INGLES_PGREF,
SAFE_CAST(MOD_COMUNI_ESCRITA_PUNT AS NUMERIC ) MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
ESTU_INSE_INDIVIDUAL, -- 100
SAFE_CAST(ESTU_NSE_INDIVIDUAL AS STRING ) ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20181` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
), 

SBTyT_20182 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
ESTU_TIENEETNIA ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
'' ESTU_ESTADOCIVIL,
ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
ESTU_OTROCOLE_TERMINO,
ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
'' ESTU_CURSODOCENTESIES, --30
'' ESTU_CURSOIESAPOYOEXTERNO,
'' ESTU_CURSOIESEXTERNA,
ESTU_SIMULACROTIPOICFES,
ESTU_ACTIVIDADREFUERZOAREAS,
ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
'' ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
FAMI_HOGARACTUAL,
FAMI_CABEZAFAMILIA,
FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_TRABAJOLABORPADRE FAMI_OCUPACIONPADRE,
FAMI_TRABAJOLABORMADRE FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
FAMI_PERSONASHOGAR, -- 50
FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
'' FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
CAST(INST_COD_INSTITUCION AS NUMERIC) INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
SAFE_CAST(ESTU_SNIES_PRGMACADEMICO AS NUMERIC) ESTU_SNIES_PRGMACADEMICO,
GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
SAFE_CAST(MOD_RAZONA_CUANTITATIVO_PGREF AS NUMERIC ) MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
SAFE_CAST(MOD_INGLES_PGREF AS NUMERIC ) MOD_INGLES_PGREF,
SAFE_CAST(MOD_COMUNI_ESCRITA_PUNT AS NUMERIC ) MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
ESTU_INSE_INDIVIDUAL, -- 100
SAFE_CAST(ESTU_NSE_INDIVIDUAL AS STRING ) ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20182` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
), 

SBTyT_20191 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
ESTU_TIENEETNIA ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
'' ESTU_ESTADOCIVIL,
ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
'' ESTU_OTROCOLE_TERMINO,
ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
'' ESTU_CURSODOCENTESIES, --30
'' ESTU_CURSOIESAPOYOEXTERNO,
'' ESTU_CURSOIESEXTERNA,
ESTU_SIMULACROTIPOICFES,
ESTU_ACTIVIDADREFUERZOAREAS,
ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
'' FAMI_HOGARACTUAL,
'' FAMI_CABEZAFAMILIA,
'' FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_TRABAJOLABORPADRE FAMI_OCUPACIONPADRE,
FAMI_TRABAJOLABORMADRE FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
'' FAMI_PERSONASHOGAR, -- 50
'' FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
'' FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
CAST(INST_COD_INSTITUCION AS NUMERIC) INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
SAFE_CAST(ESTU_SNIES_PRGMACADEMICO AS NUMERIC) ESTU_SNIES_PRGMACADEMICO,
GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
SAFE_CAST(MOD_RAZONA_CUANTITATIVO_PGREF AS NUMERIC ) MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
SAFE_CAST(MOD_INGLES_PGREF AS NUMERIC ) MOD_INGLES_PGREF,
SAFE_CAST(MOD_COMUNI_ESCRITA_PUNT AS NUMERIC ) MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
ESTU_INSE_INDIVIDUAL, -- 100
SAFE_CAST(ESTU_NSE_INDIVIDUAL AS STRING ) ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20191` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
), 

SBTyT_20192 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
'' ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
'' ESTU_ESTADOCIVIL,
CAST(ESTU_COLE_TERMINO AS STRING)ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
ESTU_OTROCOLE_TERMINO,
'' ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
'' ESTU_CURSODOCENTESIES, --30
'' ESTU_CURSOIESAPOYOEXTERNO,
'' ESTU_CURSOIESEXTERNA,
ESTU_SIMULACROTIPOICFES,
ESTU_ACTIVIDADREFUERZOAREAS,
ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
'' ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
'' FAMI_HOGARACTUAL,
'' FAMI_CABEZAFAMILIA,
'' FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_TRABAJOLABORPADRE FAMI_OCUPACIONPADRE,
FAMI_TRABAJOLABORMADRE FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
'' FAMI_PERSONASHOGAR, -- 50
'' FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
'' FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
CAST(INST_COD_INSTITUCION AS NUMERIC) INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
SAFE_CAST(ESTU_SNIES_PRGMACADEMICO AS NUMERIC) ESTU_SNIES_PRGMACADEMICO,
'' GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
NULL MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
NULL MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
NULL MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
NULL MOD_INGLES_PGREF,
NULL MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
NULL MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
ESTU_INSE_INDIVIDUAL, -- 100
SAFE_CAST(ESTU_NSE_INDIVIDUAL AS STRING ) ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20192` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
), 

SBTyT_20201 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
'' ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
'' ESTU_ESTADOCIVIL,
CAST(ESTU_COLE_TERMINO AS STRING)ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
ESTU_OTROCOLE_TERMINO,
'' ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
'' ESTU_CURSODOCENTESIES, --30
'' ESTU_CURSOIESAPOYOEXTERNO,
'' ESTU_CURSOIESEXTERNA,
'' ESTU_SIMULACROTIPOICFES,
'' ESTU_ACTIVIDADREFUERZOAREAS,
 '' ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
'' ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
'' FAMI_HOGARACTUAL,
'' FAMI_CABEZAFAMILIA,
'' FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_TRABAJOLABORPADRE FAMI_OCUPACIONPADRE,
FAMI_TRABAJOLABORMADRE FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
'' FAMI_PERSONASHOGAR, -- 50
'' FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
'' FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
CAST(INST_COD_INSTITUCION AS NUMERIC) INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
SAFE_CAST(ESTU_SNIES_PRGMACADEMICO AS NUMERIC) ESTU_SNIES_PRGMACADEMICO,
'' GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
NULL MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
NULL MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
NULL MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
NULL MOD_INGLES_PGREF,
NULL MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
NULL MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
NULL ESTU_INSE_INDIVIDUAL, -- 100
'' ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20201` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
), 

SBTyT_20202 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
'' ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
'' ESTU_ESTADOCIVIL,
CAST(ESTU_COLE_TERMINO AS STRING)ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
ESTU_OTROCOLE_TERMINO,
'' ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
'' ESTU_CURSODOCENTESIES, --30
'' ESTU_CURSOIESAPOYOEXTERNO,
'' ESTU_CURSOIESEXTERNA,
'' ESTU_SIMULACROTIPOICFES,
'' ESTU_ACTIVIDADREFUERZOAREAS,
 '' ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
'' ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
'' FAMI_HOGARACTUAL,
'' FAMI_CABEZAFAMILIA,
'' FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_TRABAJOLABORPADRE FAMI_OCUPACIONPADRE,
FAMI_TRABAJOLABORMADRE FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
'' FAMI_PERSONASHOGAR, -- 50
'' FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
'' FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
CAST(INST_COD_INSTITUCION AS NUMERIC) INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
SAFE_CAST(ESTU_SNIES_PRGMACADEMICO AS NUMERIC) ESTU_SNIES_PRGMACADEMICO,
'' GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
NULL MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
NULL MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
NULL MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
NULL MOD_INGLES_PGREF,
NULL MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
NULL MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
NULL ESTU_INSE_INDIVIDUAL, -- 100
'' ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20202` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
), 

SBTyT_20211 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
'' ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
'' ESTU_ESTADOCIVIL,
CAST(ESTU_COLE_TERMINO AS STRING)ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
ESTU_OTROCOLE_TERMINO,
'' ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
'' ESTU_CURSODOCENTESIES, --30
'' ESTU_CURSOIESAPOYOEXTERNO,
'' ESTU_CURSOIESEXTERNA,
'' ESTU_SIMULACROTIPOICFES,
'' ESTU_ACTIVIDADREFUERZOAREAS,
 '' ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
'' ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
'' FAMI_HOGARACTUAL,
'' FAMI_CABEZAFAMILIA,
'' FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_TRABAJOLABORPADRE FAMI_OCUPACIONPADRE,
FAMI_TRABAJOLABORMADRE FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
'' FAMI_PERSONASHOGAR, -- 50
'' FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
'' FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
CAST(INST_COD_INSTITUCION AS NUMERIC) INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
SAFE_CAST(ESTU_SNIES_PRGMACADEMICO AS NUMERIC) ESTU_SNIES_PRGMACADEMICO,
'' GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
NULL MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
NULL MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
NULL MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
NULL MOD_INGLES_PGREF,
NULL MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
NULL MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
NULL ESTU_INSE_INDIVIDUAL, -- 100
'' ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20211` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
), 

SBTyT_20212 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
'' ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
'' ESTU_ESTADOCIVIL,
CAST(ESTU_COLE_TERMINO AS STRING)ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
ESTU_OTROCOLE_TERMINO,
'' ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
'' ESTU_CURSODOCENTESIES, --30
'' ESTU_CURSOIESAPOYOEXTERNO,
'' ESTU_CURSOIESEXTERNA,
'' ESTU_SIMULACROTIPOICFES,
'' ESTU_ACTIVIDADREFUERZOAREAS,
 '' ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
'' ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
'' FAMI_HOGARACTUAL,
'' FAMI_CABEZAFAMILIA,
'' FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_TRABAJOLABORPADRE FAMI_OCUPACIONPADRE,
FAMI_TRABAJOLABORMADRE FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
'' FAMI_PERSONASHOGAR, -- 50
'' FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
'' FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
CAST(INST_COD_INSTITUCION AS NUMERIC) INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
SAFE_CAST(ESTU_SNIES_PRGMACADEMICO AS NUMERIC) ESTU_SNIES_PRGMACADEMICO,
'' GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
NULL MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
NULL MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
NULL MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
NULL MOD_INGLES_PGREF,
NULL MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
NULL MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
NULL ESTU_INSE_INDIVIDUAL, -- 100
'' ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20212` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
), 

SBTyT_20221 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
'' ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_RESIDE_MCPIO,
'' ESTU_ESTADOCIVIL,
CAST(ESTU_COLE_TERMINO AS STRING)ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
'' ESTU_OTROCOLE_TERMINO,
'' ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
'' ESTU_CURSODOCENTESIES, --30
'' ESTU_CURSOIESAPOYOEXTERNO,
'' ESTU_CURSOIESEXTERNA,
'' ESTU_SIMULACROTIPOICFES,
'' ESTU_ACTIVIDADREFUERZOAREAS,
 '' ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
'' ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
'' FAMI_HOGARACTUAL,
'' FAMI_CABEZAFAMILIA,
'' FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_TRABAJOLABORPADRE FAMI_OCUPACIONPADRE,
FAMI_TRABAJOLABORMADRE FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
'' FAMI_PERSONASHOGAR, -- 50
'' FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
'' FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
CAST(INST_COD_INSTITUCION AS NUMERIC) INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
SAFE_CAST(ESTU_SNIES_PRGMACADEMICO AS NUMERIC) ESTU_SNIES_PRGMACADEMICO,
'' GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
'' ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
NULL MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
NULL MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
NULL MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
NULL MOD_INGLES_PGREF,
NULL MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
NULL MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
NULL ESTU_INSE_INDIVIDUAL, -- 100
'' ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20221` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
), 

SBTyT_20222 AS (
SELECT  
ESTU_TIPODOCUMENTO,
ESTU_NACIONALIDAD,
ESTU_GENERO,
ESTU_FECHANACIMIENTO,
PERIODO, --5
ESTU_CONSECUTIVO,
ESTU_ESTUDIANTE,
ESTU_PAIS_RESIDE,
'' ESTU_ETNIA,
ESTU_DEPTO_RESIDE, --10
ESTU_COD_DEPTO_PRESENTACION ESTU_COD_RESIDE_DEPTO,
ESTU_MCPIO_RESIDE,
ESTU_COD_MCPIO_PRESENTACION ESTU_COD_RESIDE_MCPIO,
'' ESTU_ESTADOCIVIL,
CAST(ESTU_COLE_TERMINO AS STRING)ESTU_COLE_TERMINO,--15
ESTU_CODDANE_COLE_TERMINO,
ESTU_COD_COLE_MCPIO_TERMINO,
ESTU_OTROCOLE_TERMINO,
'' ESTU_TITULOOBTENIDOBACHILLER,
NULL ESTU_ANO_EXAMENESTADO_SB11, --20
'' ESTU_SEMESTRE_EXAMENESTADOSB11,
'' ESTU_PORCENTAJECREDITOSAPROB,
ESTU_VALORMATRICULAUNIVERSIDAD,
ESTU_PAGOMATRICULABECA,
ESTU_PAGOMATRICULACREDITO, -- 25
ESTU_PAGOMATRICULAPADRES,
ESTU_PAGOMATRICULAPROPIO,
'' ESTU_COMOCAPACITOEXAMENSB11,
'' ESTU_TOMO_CURSOPREPARACION,
'' ESTU_CURSODOCENTESIES, --30
'' ESTU_CURSOIESAPOYOEXTERNO,
'' ESTU_CURSOIESEXTERNA,
'' ESTU_SIMULACROTIPOICFES,
'' ESTU_ACTIVIDADREFUERZOAREAS,
 '' ESTU_ACTIVIDADREFUERZOGENERIC, --35
ESTU_TIPODOCUMENTOSB11,
'' ESTU_SEMESTRECURSA,
'' ESTU_ULTIMOGRADOAPROBO,
NULL ESTU_ANOTERMINOULTIMOGRADO,
'' ESTU_VECESPRESENTOEXAMEN, --40
'' FAMI_HOGARACTUAL,
'' FAMI_CABEZAFAMILIA,
'' FAMI_NUMPERSONASACARGO,
FAMI_EDUCACIONPADRE,
FAMI_EDUCACIONMADRE, -- 45
FAMI_TRABAJOLABORPADRE FAMI_OCUPACIONPADRE,
FAMI_TRABAJOLABORMADRE FAMI_OCUPACIONMADRE,
FAMI_ESTRATOVIVIENDA,
'' FAMI_NIVEL_SISBEN,
'' FAMI_PERSONASHOGAR, -- 50
'' FAMI_CUARTOSHOGAR,
'' FAMI_PISOS_HOGAR,
FAMI_TIENEINTERNET,
'' FAMI_TIENESERVICIOTV,
FAMI_TIENECOMPUTADOR, -- 55
FAMI_TIENELAVADORA,
'' FAMI_INGRESO_FMILIAR_MENSUAL,
CASE WHEN  ESTU_HORASSEMANATRABAJA = '0' THEN 'NO'
WHEN  ESTU_HORASSEMANATRABAJA IS NULL THEN NULL 
ELSE 'SI' END ESTU_TRABAJA_ACTUALMENTE,
ESTU_HORASSEMANATRABAJA,
CAST(INST_COD_INSTITUCION AS NUMERIC) INST_COD_INSTITUCION, -- 60
INST_NOMBRE_INSTITUCION,
ESTU_PRGM_ACADEMICO,
SAFE_CAST(ESTU_SNIES_PRGMACADEMICO AS NUMERIC) ESTU_SNIES_PRGMACADEMICO,
'' GRUPOREFERENCIA,
ESTU_PRGM_CODMUNICIPIO,-- 65
ESTU_PRGM_MUNICIPIO,
ESTU_PRGM_DEPARTAMENTO,
ESTU_NIVEL_PRGM_ACADEMICO,
ESTU_METODO_PRGM,
ESTU_NUCLEO_PREGRADO, -- 70
ESTU_INST_CODMUNICIPIO,
ESTU_INST_MUNICIPIO,
ESTU_INST_DEPARTAMENTO,
INST_CARACTER_ACADEMICO,
INST_ORIGEN, -- 75
ESTU_PRIVADO_LIBERTAD,
ESTU_COD_MCPIO_PRESENTACION,
ESTU_MCPIO_PRESENTACION,
ESTU_DEPTO_PRESENTACION,
ESTU_COD_DEPTO_PRESENTACION, -- 80
MOD_RAZONA_CUANTITAT_PUNT,
MOD_RAZONA_CUANTITATIVO_PNAL,
NULL MOD_RAZONA_CUANTITATIVO_PGREF,
MOD_LECTURA_CRITICA_PUNT,
MOD_LECTURA_CRITICA_PNAL, -- 85
NULL MOD_LECTURA_CRITICA_PGREF,
MOD_COMPETEN_CIUDADA_PUNT,
MOD_COMPETEN_CIUDADA_PNAL,
NULL MOD_COMPETEN_CIUDADA_PGREF,
MOD_INGLES_PUNT, -- 90
MOD_INGLES_DESEM,
MOD_INGLES_PNAL,
NULL MOD_INGLES_PGREF,
NULL MOD_COMUNI_ESCRITA_PUNT,
MOD_COMUNI_ESCRITA_DESEM, -- 95 
MOD_COMUNI_ESCRITA_PNAL,
NULL MOD_COMUNI_ESCRITA_PGREF,
PUNT_GLOBAL,
PERCENTIL_GLOBAL,
NULL ESTU_INSE_INDIVIDUAL, -- 100
'' ESTU_NSE_INDIVIDUAL,
ESTU_ESTADOINVESTIGACION,
 FROM `ph-jabri.SABER_TyT.SBTyT_20222` WHERE ESTU_ESTADOINVESTIGACION = 'PUBLICAR'
 -- -- LIMIT 5
), 
SBTYT AS (
  SELECT *   FROM SBTyT_20161
  UNION ALL 
  SELECT *   FROM SBTyT_20162
  UNION ALL 
  SELECT *   FROM SBTyT_20171
  UNION ALL 
  SELECT *   FROM SBTyT_20172
  UNION ALL 
  SELECT *   FROM SBTyT_20181
  UNION ALL 
  SELECT *   FROM SBTyT_20182
  UNION ALL 
  SELECT *   FROM SBTyT_20191
  UNION ALL 
  SELECT *   FROM SBTyT_20192
  UNION ALL 
  SELECT *   FROM SBTyT_20201
  UNION ALL 
  SELECT *   FROM SBTyT_20202
  UNION ALL 
  SELECT *   FROM SBTyT_20211
  UNION ALL 
  SELECT *   FROM SBTyT_20212
  UNION ALL 
  SELECT *   FROM SBTyT_20221
  UNION ALL 
  SELECT *   FROM SBTyT_20222
)
SELECT * FROM SBTYT