WITH 
Years AS (
  SELECT '2012' AS Year
  UNION ALL SELECT '2013'
  UNION ALL  SELECT '2014'
  UNION ALL  SELECT '2015'
  UNION ALL  SELECT '2016'
  UNION ALL  SELECT '2017'
  UNION ALL  SELECT '2018'
  UNION ALL  SELECT '2019'
  UNION ALL  SELECT '2020'
),
Sexos AS (
  SELECT 'F' AS Sexo
  UNION ALL
  SELECT 'M'
),
UNIQUE_SCHOOLS AS (
  SELECT DISTINCT 
codigo_dane,
codigo_dane_sede ,
cons_sede
 FROM `ph-jabri.SIMAT_SNIES.SIMAT_SNIES` 
),
UNIQUE_SCHOOLS_SEX_YEAR AS ( 
SELECT * FROM UNIQUE_SCHOOLS
INNER JOIN Years ON 1=1
INNER JOIN Sexos  ON  1=1
),
ENROLLED_IN_ENG_ARCHITECTURE_URBAN_ AS (
SELECT codigo_dane ||' - '||  codigo_dane_sede  ||' - '|| cons_sede ID_1_2012,
YEAR_INFO YEAR_SCHOOLING_LAST_GRADE, SEXO_BIOLOGICO,  
IFNULL(SUM(case when AREA_CONOCIMIENTO = 'ENGINEERING, ARCHITECTURE, URBAN PLANNING, AND RELATED FIELDS'  
then 1 else 0 end), 0) ENROLLED_IN_ENG_ARCHITECTURE_URBAN
FROM  `ph-jabri.SIMAT_SNIES.SIMAT_SNIES` 
WHERE LEVEL = 'University Program'  AND AREA_CONOCIMIENTO = 'ENGINEERING, ARCHITECTURE, URBAN PLANNING, AND RELATED FIELDS'  
GROUP BY 1,2 ,3
) ,
ENROLLED_IN_EDUCATION_SCIENCES_ AS (
SELECT codigo_dane ||' - '||  codigo_dane_sede  ||' - '|| cons_sede ID_1_2012,
YEAR_INFO YEAR_SCHOOLING_LAST_GRADE, SEXO_BIOLOGICO,  
IFNULL(SUM(case when AREA_CONOCIMIENTO = 'EDUCATION SCIENCES'  
then 1 else 0 end), 0) ENROLLED_IN_EDUCATION_SCIENCES
FROM  `ph-jabri.SIMAT_SNIES.SIMAT_SNIES` 
WHERE LEVEL = 'University Program'  AND AREA_CONOCIMIENTO = 'EDUCATION SCIENCES'  
GROUP BY 1,2 ,3
) ,
ENROLLED_IN_AGRO_ AS (
SELECT codigo_dane ||' - '||  codigo_dane_sede  ||' - '|| cons_sede ID_1_2012,
YEAR_INFO YEAR_SCHOOLING_LAST_GRADE, SEXO_BIOLOGICO,  
IFNULL(SUM(case when AREA_CONOCIMIENTO = 'AGRONOMY, VETERINARY MEDICINE, AND RELATED FIELDS'  
then 1 else 0 end), 0) ENROLLED_IN_AGRO
FROM  `ph-jabri.SIMAT_SNIES.SIMAT_SNIES` 
WHERE LEVEL = 'University Program'  AND AREA_CONOCIMIENTO = 'AGRONOMY, VETERINARY MEDICINE, AND RELATED FIELDS'  
GROUP BY 1,2 ,3
) ,
ENROLLED_IN_SOCIAL_SCIENCE_ AS (
SELECT codigo_dane ||' - '||  codigo_dane_sede  ||' - '|| cons_sede ID_1_2012,
YEAR_INFO YEAR_SCHOOLING_LAST_GRADE, SEXO_BIOLOGICO,  
IFNULL(SUM(case when AREA_CONOCIMIENTO = 'SOCIAL SCIENCES AND HUMANITIES'  
then 1 else 0 end), 0) ENROLLED_IN_SOCIAL_SCIENCE
FROM  `ph-jabri.SIMAT_SNIES.SIMAT_SNIES` 
WHERE LEVEL = 'University Program'  AND AREA_CONOCIMIENTO = 'SOCIAL SCIENCES AND HUMANITIES'  
GROUP BY 1,2 ,3
) ,
ENROLLED_FINE_ARTS_ AS (
SELECT codigo_dane ||' - '||  codigo_dane_sede  ||' - '|| cons_sede ID_1_2012,
YEAR_INFO YEAR_SCHOOLING_LAST_GRADE, SEXO_BIOLOGICO,  
IFNULL(SUM(case when AREA_CONOCIMIENTO = 'FINE ARTS'  
then 1 else 0 end), 0) ENROLLED_FINE_ARTS
FROM  `ph-jabri.SIMAT_SNIES.SIMAT_SNIES` 
WHERE LEVEL = 'University Program'  AND AREA_CONOCIMIENTO = 'FINE ARTS'  
GROUP BY 1,2 ,3
)  ,
ENROLLED_ECONOMICS_BUSINESS_ AS (
SELECT codigo_dane ||' - '||  codigo_dane_sede  ||' - '|| cons_sede ID_1_2012,
YEAR_INFO YEAR_SCHOOLING_LAST_GRADE, SEXO_BIOLOGICO,  
IFNULL(SUM(case when AREA_CONOCIMIENTO  LIKE  '%ECONOMICS, BUSINESS%'  
then 1 else 0 end), 0) ENROLLED_ECONOMICS_BUSINESS
FROM  `ph-jabri.SIMAT_SNIES.SIMAT_SNIES` 
WHERE LEVEL = 'University Program'  AND AREA_CONOCIMIENTO LIKE  '%ECONOMICS, BUSINESS%'  
GROUP BY 1,2 ,3
) ,
ENROLLED_HEALTH_SCIENCES_ AS (
SELECT codigo_dane ||' - '||  codigo_dane_sede  ||' - '|| cons_sede ID_1_2012,
YEAR_INFO YEAR_SCHOOLING_LAST_GRADE, SEXO_BIOLOGICO,  
IFNULL(SUM(case when AREA_CONOCIMIENTO  LIKE  '%HEALTH%'  
then 1 else 0 end), 0) ENROLLED_HEALTH_SCIENCES
FROM  `ph-jabri.SIMAT_SNIES.SIMAT_SNIES` 
WHERE LEVEL = 'University Program'  AND AREA_CONOCIMIENTO LIKE  '%HEALTH%'  
GROUP BY 1,2 ,3
) 
-- SELECT * FROM  ENROLLED_IN_ENG_ARCHITECTURE_URBAN --UNIQUE_SCHOOLS_SEX_YEAR 
-- ORDER BY 2
SELECT codigo_dane ||' - '||  codigo_dane_sede  ||' - '|| cons_sede ID_1_2012,
YEAR_INFO YEAR_SCHOOLING_LAST_GRADE, SEXO_BIOLOGICO,  
IFNULL(SUM(case when AREA_CONOCIMIENTO  LIKE  '%HEALTH%'  
then 1 else 0 end), 0) ENROLLED_HEALTH_SCIENCES
FROM  `ph-jabri.SIMAT_SNIES.SIMAT_SNIES` 
WHERE LEVEL = 'University Program'  AND AREA_CONOCIMIENTO LIKE  '%HEALTH%'  
GROUP BY 1,2 ,3